/**
 * dorkhub voice — "Quiet dev-native" (locked M0).
 * Rules: generosity verbs (share, fork, take, borrow, tinker). Banned: buy, sell, hire,
 * rocket emoji, growth-speak. Errors take the blame. Empty states are invitations.
 * Zero-stat projects show absence, never "0".
 */
export const copy = {
  ctaPrimary: 'show your thing',
  like: '++',
  save: 'save',
  saved: 'saved',
  follow: 'follow',
  following: 'following',
  emptyFeed: 'nothing here yet — go find something weird',
  emptyFeedLead: 'nothing here yet —',
  emptyFeedLink: 'go find something weird',
  relatedTitle: 'more like this',
  recsTitle: 'because you starred',
  recsImportNudge: 'bring your github stars — we’ll find more like them',
  navWeird: 'weird',
  profileEmptyProjects: 'nothing published here yet',
  projectNoReadme: 'no readme yet — the code speaks for itself',
  projectDraftBadge: 'draft — only you can see this',
  projectRefreshThrottled: 'just synced — give github five minutes to breathe',
  newTitle: 'pick a thing to show',
  newSubtitle: 'public repos only — drafts stay yours until you publish',
  newNoRepos: 'no public repos found — push something weird first',
  newRepoListTruncated: 'showing your 500 most recently updated repos',
  newRepoUnavailable: 'github wouldn’t hand that repo over — try again?',
  newRepoNotYours: 'that repo isn’t yours to show',
  newRepoTaken: 'someone already showcases this repo here',
  settingsProjectsTitle: 'your projects',
  settingsEmptyProjects: 'nothing here yet — go show your thing',
  settingsDeleteConfirm: 'remove this project from dorkhub? the repo stays yours on github.',
  actionPublish: 'publish',
  actionUnpublish: 'unpublish',
  actionRefresh: 'refresh from github',
  actionSave: 'save',
  actionRemove: 'remove',
  sortTrending: 'trending',
  loadMore: 'load more',
  loadingMore: 'loading…',
  savedTitle: 'saved',
  savedEmpty: 'nothing saved yet — go find something worth keeping',
  followingTitle: 'following',
  followingEmpty: 'you’re not following anyone yet — go find your people',
  listsTitle: 'lists',
  listNew: 'new list',
  listNewPlaceholder: 'name your list',
  listDescriptionPlaceholder: 'what ties these together?',
  listEmpty: 'nothing in this list yet',
  listsEmptyOwn: 'no lists yet — start one and put your favorite finds together',
  listsEmptyVisitor: 'no public lists yet',
  listAdd: 'add to list',
  listCapHit: 'you’ve hit 50 lists — the cap for now',
  listItemCapHit: 'this list is full — 400 is the cap for now',
  listDeleteConfirm: 'delete this list? the projects in it stay put.',
  listPrivateBadge: 'private',
  listVisibilityPublic: 'public',
  listVisibilityPrivate: 'private',
  tagsTitle: 'browse by tag',
  tagsStackLabel: 'stacks',
  tagsTopicLabel: 'topics',
  signInPrompt: 'sign in to join in',
  searchPlaceholder: 'search projects…',
  searchEmpty: 'nothing yet — try fewer letters',
  searchGroupProjects: 'projects',
  searchGroupPeople: 'people',
  searchGroupTags: 'tags',
  importTitle: 'bring your stars',
  importSubtitle:
    'we’ll match your public github stars against the gallery — the rest go live right after',
  importStart: 'import my stars',
  importRunning: 'reading your stars…',
  importDoneHere: 'of your stars are already here',
  importDoneOwn: 'of your own repos aren’t listed yet',
  importEmpty: 'no public stars found — go wander github first',
  importSkip: 'later — take me home',
  importMaterializing: 'putting them on the wall…',
  importDoneLive: 'of your stars just went live',
  importDonePolishing: 'more going live automatically — check back in a bit',
  sortNewest: 'newest',
  claimTitle: 'we hand-picked your work',
  claimBody: 'this page is yours if you want it — or we’ll remove it. no strings.',
  claimAccept: 'claim my page',
  claimDecline: 'remove my stuff',
  claimDeclined: 'done — your pages are unpublished. change your mind anytime by signing back in.',
  adminQueueTitle: 'review queue',
  adminSourcesTitle: 'sources',
  adminClaimsTitle: 'claims',
  reportAction: 'report',
  reportDialogTitle: 'report this project',
  reportReasonLabel: 'what’s wrong?',
  reportReasons: {
    spam: 'spam or seo bait',
    malware: 'malware or sketchy code',
    'not-a-project': 'not actually a project',
    abuse: 'hateful or abusive',
    other: 'something else',
  },
  reportNoteLabel: 'more context — optional',
  reportSubmit: 'send report',
  reportSubmitting: 'sending…',
  reportThanks: 'got it — a human will take a look',
  reportAlready: 'you already reported this one — it’s on the list',
  reportRateLimited: 'that’s a lot of reports for one day — try again tomorrow',
  error: 'something broke on our end — not you, us. try again?',
  notFound: '404: page not found\n// maybe it shipped, maybe it never existed',
  forkNudge: 'fork it — it’s yours',
  heroHeadline: 'a home for the things you build for fun',
  heroSub:
    'connect github, pick the repos you love, give each one a page. free to browse, free to fork.',
  footerLine: 'made by dorks, for dorks',
  browseCta: 'browse projects',
  signIn: 'sign in with GitHub',
  isList: ['show-and-tell for things you built', 'forkable by design', 'free, forever'],
  isntList: ['a leaderboard', 'a marketplace', 'a hiring portfolio'],
} as const;
