/**
 * dorkhub voice — "Quiet dev-native" (locked M0).
 * Rules: generosity verbs (share, fork, take, borrow, tinker). Banned: buy, sell, hire,
 * rocket emoji, growth-speak. Errors take the blame. Empty states are invitations.
 * Zero-stat projects show absence, never "0".
 */
export const copy = {
  ctaPrimary: 'show your thing',
  like: '++',
  save: 'save',
  saved: 'saved',
  follow: 'follow',
  following: 'following',
  emptyFeed: 'nothing here yet — go find something weird',
  profileEmptyProjects: 'nothing published here yet',
  projectNoReadme: 'no readme yet — the code speaks for itself',
  projectDraftBadge: 'draft — only you can see this',
  projectRefreshThrottled: 'just synced — give github five minutes to breathe',
  newTitle: 'pick a thing to show',
  newSubtitle: 'public repos only — drafts stay yours until you publish',
  newNoRepos: 'no public repos found — push something weird first',
  newRepoListTruncated: 'showing your 500 most recently updated repos',
  newRepoUnavailable: 'github wouldn’t hand that repo over — try again?',
  newRepoNotYours: 'that repo isn’t yours to show',
  newRepoTaken: 'someone already showcases this repo here',
  settingsProjectsTitle: 'your projects',
  settingsEmptyProjects: 'nothing here yet — go show your thing',
  settingsDeleteConfirm: 'remove this project from dorkhub? the repo stays yours on github.',
  actionPublish: 'publish',
  actionUnpublish: 'unpublish',
  actionRefresh: 'refresh from github',
  actionSave: 'save',
  actionRemove: 'remove',
  error: 'something broke on our end — not you, us. try again?',
  notFound: '404: page not found\n// maybe it shipped, maybe it never existed',
  forkNudge: 'fork it — it’s yours',
  heroHeadline: 'a home for the things you build for fun',
  heroSub:
    'connect github, pick the repos you love, give each one a page. free to browse, free to fork.',
  footerLine: 'made by dorks, for dorks',
  browseCta: 'browse projects',
  signIn: 'sign in with GitHub',
  isList: ['show-and-tell for things you built', 'forkable by design', 'free, forever'],
  isntList: ['a leaderboard', 'a marketplace', 'a hiring portfolio'],
} as const;
